/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppsAppContainer: typeof import('./components/apps/AppContainer.vue')['default']
    CollapesCollapsibleItem: typeof import('./components/collapes/collapsibleItem.vue')['default']
    Default: typeof import('./bin/platform/hermes/layouts/default.vue')['default']
    DivisorWidget: typeof import('./bin/platform/dashboard/components/divisorWidget/components/DivisorWidget.vue')['default']
    GenericFooter: typeof import('./components/generic/footer.vue')['default']
    GenericGeneralSpinner: typeof import('./components/generic/GeneralSpinner.vue')['default']
    GenericPreloader: typeof import('./components/generic/Preloader.vue')['default']
    GenericUserAvatar: typeof import('./components/generic/UserAvatar.vue')['default']
    GlobalWidgetsGlobalWidgetWrapper: typeof import('./components/globalWidgets/GlobalWidgetWrapper.vue')['default']
    GlobalWidgetsWidgetArea: typeof import('./components/globalWidgets/WidgetArea.vue')['default']
    GlobalWidgetsWidgetWrapper: typeof import('./components/globalWidgets/WidgetWrapper.vue')['default']
    HeaderHeader: typeof import('./components/header/header.vue')['default']
    HeaderNotifications: typeof import('./components/header/Notifications.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginForgotPassword: typeof import('./components/login/ForgotPassword.vue')['default']
    LoginFormWrapperComponent: typeof import('./components/login/FormWrapperComponent.vue')['default']
    LoginLoginForm: typeof import('./components/login/LoginForm.vue')['default']
    LoginResetPassword: typeof import('./components/login/ResetPassword.vue')['default']
    ModalModalComponent: typeof import('./components/modal/ModalComponent.vue')['default']
    PluginsFormGeneratorFieldsCheckBox: typeof import('./components/plugins/formGenerator/fields/CheckBox.vue')['default']
    PluginsFormGeneratorFieldsDefaultField: typeof import('./components/plugins/formGenerator/fields/DefaultField.vue')['default']
    PluginsFormGeneratorFieldsDropdownSelect: typeof import('./components/plugins/formGenerator/fields/DropdownSelect.vue')['default']
    PluginsFormGeneratorFieldsFilepond: typeof import('./components/plugins/formGenerator/fields/Filepond.vue')['default']
    PluginsFormGeneratorFieldsFIleUpload: typeof import('./components/plugins/formGenerator/fields/FIleUpload.vue')['default']
    PluginsFormGeneratorFieldsItemsTable: typeof import('./components/plugins/formGenerator/fields/ItemsTable.vue')['default']
    PluginsFormGeneratorFieldsListPage: typeof import('./components/plugins/formGenerator/fields/ListPage.vue')['default']
    PluginsFormGeneratorFieldsListType: typeof import('./components/plugins/formGenerator/fields/ListType.vue')['default']
    PluginsFormGeneratorFieldsRecordFindAddList: typeof import('./components/plugins/formGenerator/fields/RecordFindAddList.vue')['default']
    PluginsFormGeneratorFieldsRecordFinder: typeof import('./components/plugins/formGenerator/fields/RecordFinder.vue')['default']
    PluginsFormGeneratorFieldsSearchList: typeof import('./components/plugins/formGenerator/fields/SearchList.vue')['default']
    PluginsFormGeneratorFormGenerator: typeof import('./components/plugins/formGenerator/FormGenerator.vue')['default']
    PluginsFormGeneratorTabsFormGenerator: typeof import('./components/plugins/formGenerator/TabsFormGenerator.vue')['default']
    ResourceBuilder: typeof import('./bin/platform/hermes/components/resource/builder.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchbarSearchbar: typeof import('./components/searchbar/Searchbar.vue')['default']
    SearchbarSearchBarMobile: typeof import('./components/searchbar/SearchBarMobile.vue')['default']
    SearchbarSearchContexts: typeof import('./components/searchbar/SearchContexts.vue')['default']
    SidebarApplicationLogo: typeof import('./components/sidebar/ApplicationLogo.vue')['default']
    SidebarBottomLinks: typeof import('./components/sidebar/BottomLinks.vue')['default']
    SidebarMainSectionLinks: typeof import('./components/sidebar/MainSectionLinks.vue')['default']
    SidebarRightSideBar: typeof import('./components/sidebar/RightSideBar.vue')['default']
    SidebarSidebar: typeof import('./components/sidebar/sidebar.vue')['default']
    SidebarUserProfilePopper: typeof import('./components/sidebar/UserProfilePopper.vue')['default']
    SkeletonLoaderWrapper: typeof import('./components/SkeletonLoaderWrapper.vue')['default']
    WelcomeWidgetComponent: typeof import('./bin/platform/dashboard/components/welcomeWidget/components/WelcomeWidgetComponent.vue')['default']
    WidgetAreaWidget: typeof import('./bin/platform/dashboard/components/widgetAreaWidget/components/WidgetAreaWidget.vue')['default']
  }
}
